In [ ]:
import numpy as np
# Creating arrays
arr = np.array([1,2,3,4,5])
print(arr)



[1 2 3 4 5]


In [ ]:
zeros_arr = np.zeros((3,3), dtype=int)
print(zeros_arr)
ones_arr = np.ones((2,2), dtype=float)
print(ones_arr)
#ARANGE
arange_arr = np.arange(10)
print(arange_arr)
# array manipulaton
arr = np.array([1,2,3,4,5])
reshaped_arr = arr.reshape(5,1)
print(reshaped_arr)
# slicing
sliced_arr = arr[2:4]
print(sliced_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1.]
 [1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]]
[3 4]


In [ ]:
# transpose of array
a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)
# Split
b=np.split(a,4)
print(b)

[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d = np.linalg.eig(c)
print(d)

[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
data = np.loadtxt("/content/drive/MyDrive/DATASET/data.txt",dtype=int)
d = np.savetxt("/content/date.txt",data)
print(d)
print(data)

None
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
import numpy as np
arange_arr = np.arange(0,100,5)
print(arange_arr)
d = np.savetxt("/content/prasad.txt",arange_arr)
print(d)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
None


In [ ]:
a=np.random.rand()
print(a)

0.670983261492736


In [ ]:
b=np.random.randint(0,2)
print(b)

1


In [ ]:
a=np.array([[2,3],[4,5]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)


[[2 3]
 [4 5]]
<class 'numpy.ndarray'>
2
(2, 2)


In [ ]:
a=np.linspace(0.8,2,5)
print(a)

[0.8 1.1 1.4 1.7 2. ]


In [ ]:
import numpy as np
arr=np.arange(30).reshape(1,5,6)
print(arr)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a*b)
a@b
c=np.dot(a,b)
print(c)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
from numpy import random
a=np.ones((2,2),dtype=int)
print(a)
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

[[1 1]
 [1 1]]
4
[2 2]
[2 2]


In [ ]:
b=np.floor(np.random.rand(2,2))
a=np.ceil(np.random.rand(2,2))
print(b)
print(a)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.cumsum(axis=1))


[[1 2]
 [3 4]]
[[1 3]
 [3 7]]


In [ ]:
a = np.array([2,3,5,6])
print(a.cumsum())

[ 2  5 10 16]


In [ ]:
a = np.array([2,3,4,5,6,7])

print(a.resize(3,2))
print(a)
print(a.shape)

None
[[2 3]
 [4 5]
 [6 7]]
(3, 2)


In [ ]:
a = np.array([2,3,4,5,6,7])
print(a.resize(2,3))
b = np.array([2,3,4,5,6,7])
print(b.resize(2,3))
print(np.vstack((a,b)))

None
None
[[2 3 4]
 [5 6 7]
 [2 3 4]
 [5 6 7]]


In [ ]:
a = np.array([2,3,4,5,6,7])
print(a.resize(2,3))
b = np.array([2,3,4,5,6,7])
print(b.resize(2,3))
print(np.hstack((a,b)))

None
None
[[2 3 4 2 3 4]
 [5 6 7 5 6 7]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


#
no of rows become no of group,,,,
coloumns become rows,,,,,
group become coloumns

In [ ]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a=np.full((2,2),3)
print(a)
print(a.itemsize)

[[3 3]
 [3 3]]
8


In [ ]:
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


we can arrange the array as vertically and then we need perform the .cross

In [ ]:
x=np.array([1.4,2.6,3.3,4.7,5.87,6.45,7.7])
a=np.rint(x)
print(a)


[1. 3. 3. 5. 6. 6. 8.]


In [ ]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])
c=np.true_divide(x,y)
print(c)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
x=np.array([1,1,2,2,3,3,4,4,5,5])
y=np.unique(x)
print(y)

[1 2 3 4 5]


In [ ]:
x=np.array([[1,2,3,4,5],[1,2,3,4,5]])
y=np.array([[6,7,8,9,10],[6,7,8,9,10]])
z=np.union1d(x,y)
print(z)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
x=np.array([[1,2,3,4,5],[1,2,3,4,5]])
y=np.array([[6,7,4,9,10],[6,7,5,9,10]])
z=np.intersect1d(x,y)
print(z)

[4 5]


In [ ]:
x=np.array([[1,2,3,4,5],[1,2,3,4,5]])
y=np.array([[6,7,4,9,10],[6,7,5,9,10]])
z=np.setdiff1d(x,y)
print(z)

[1 2 3]


In [ ]:
a=8
b=6
c=np.hypot(a,b)
print(c)

10.0


In [ ]:
x=np.sin(0)
print(x)

0.0


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.divmod(a,b)
print(c)

(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.mod(a,b)
print(c)

[10  0  0 15  0  0]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.divide(a,b)
print(c)

[ 0.5  1.  15.   1.6  2.   2. ]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.multiply(a,b)
print(c)

[ 200  441   60 1000 1250 1800]


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
print(x)

[[ 0.0356012   1.62069732 -0.25849651]
 [ 0.30428538 -0.9717639  -1.2020672 ]]


In [ ]:
from numpy import random
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)

[[ 1.15677524  1.8083006   3.41972919]
 [ 4.60613877  2.01742951 -0.61360261]]


loc:mean value,scale:standard diviation,size=size of array

In [ ]:
x=random.binomial(n=12,p=0.5,size=10)
print(x)

[5 6 5 6 3 9 8 8 6 8]


In [ ]:
x=random.poisson(lam=2,size=10)
print(x)

[2 2 1 3 2 1 3 1 4 2]


In [ ]:
x=random.choice([1,2,3,4,5])
print(x)

1


In [ ]:
x=random.choice([3,5],p=(0.5,0.5),size=(3,5))
print(x)

[[5 3 3 3 5]
 [5 3 3 5 5]
 [5 3 3 3 3]]
